Improved Grid configuration
ploteria/ploteria pull request #23
Opened 2020-07-02 18:26 UTC by mfep

Reworked the grid configuration structure (Closes #9). With that the following properties can be set:

- Whether to show major/minor grid (per axis)
- Whether to render the grid in front of the plot or behind it (global, applies to all grid lines)
- The color, weight and line type of the grid lines (per major/minor)

Technical changes:
- The `grid` module is refactored out of the `axis` module, because not all settings are axis dependent
- Showcasing the new options in the examples section

2020-07-17 10:21 UTC, mfep commented
Any input on this, please?
@Dylan-DPC @Darksonn @bheisler

2020-07-17 10:44 UTC, Dylan-DPC-zz requested changes

2020-07-17 10:44 UTC, Dylan-DPC commented on src/axis.rs
>  impl Default for AxisProperties {
since it looks like we are using all the default values, we can derive default instead and get rid of the impl.

2020-07-17 10:44 UTC, Dylan-DPC commented on src/grid.rs
> +impl Default for GridOptions {
we can derive defaults here

2020-07-17 10:44 UTC, Dylan-DPC commented on src/lib.rs
> +    pub fn configure_grid<F: FnOnce(&mut GridOptions) -> &mut GridOptions>(
tiny tidbit - would prefer a `where` style instead of putting the bounds inside the `<>`

2020-07-19 07:55 UTC, mfep commented on src/axis.rs
>  impl Default for AxisProperties {
Unfortunately this is not possible because of the non-default value of the `scale_factor` field.

2020-07-19 08:18 UTC, mfep commented on src/grid.rs
> +impl Default for GridOptions {
This is the `ploteria::Default` trait which cannot be derived from. I think it is a conscious choice not to use `std::Default` (see comment at lib.rs:781).

2020-07-19 08:25 UTC, mfep commented on src/lib.rs
> +    pub fn configure_grid<F: FnOnce(&mut GridOptions) -> &mut GridOptions>(
Agreed. Fixed all occurrences.

2020-09-14 19:27 UTC, mfep commented
Bump, bump! Any word on this, @Dylan-DPC ?

2024-03-04 10:21 UTC, closed without merging